
language: "sv"

source_type: xml

token_chunk: <sentence>
saldo.precision: ""

classes:
    token: segment.token
    "token:word": <token>:misc.word
    "token:sense": <token>:wsd.sense
    sentence: segment.sentence


remove_export_namespaces: true

xml_export.filename: "{doc}_export.xml"

# Korp: password protected corpus
protected: false
