id: treetagger-corpus
name: TreeTagger test corpus
language: nld

# Elements and attributes from the source XML that we want to be available as input for other annotations
xml_elements:
    - text

sentence_chunk: <text>

annotations:
    - text
    - <text>:readability.lix
    - <sentence>
    - <token>
    - <token:pos>
    - <token:msd>
    - <token:baseform>

classes:
    text: text
    token: segment.token
    "token:pos": <token>:treetagger.pos
    "token:msd": <token>:treetagger.msd
    "token:baseform": <token>:treetagger.baseform
