#===============================================================================
# Date/Time Annotation Presets
#===============================================================================

all:
    - <text>:dateformat.datefrom
    - <text>:dateformat.dateto
    - <text>:dateformat.timefrom
    - <text>:dateformat.timeto
