#===============================================================================
# FreeLing Annotation Presets
#===============================================================================

languages:
    - ast
    - fra"
    - glg
    - ita
    - nob
    - rus
    - slv


classes:
    sentence: freeling.sentence
    token: freeling.token


presets:
    all:
        - token
        - sentence

    token:
        - freeling.token:freeling.word
        - freeling.token:freeling.upos
        - freeling.token:freeling.pos
        - freeling.token:freeling.baseform

    sentence:
        - freeling.sentence:misc.id
