#===============================================================================
# Paragraph Annotation Presets
#===============================================================================

all:
    - <paragraph>:misc.id
    - <paragraph>.geo.geo_context as geo
