#===============================================================================
# Paragraph Annotation Presets
#===============================================================================

presets:
    all:
        - <paragraph>:misc.id
        - <paragraph>.geo.geo_context as geo
