#===============================================================================
# Stanford Parser Annotation Presets
#===============================================================================

all:
    - token
    - sentence

token:
    - stanford.token:stanford.word
    - stanford.token:stanford.ref
    - stanford.token:stanford.pos
    - stanford.token:stanford.upos
    - stanford.token:stanford.baseform
    - stanford.token:stanford.ne_type
    - stanford.token:stanford.dephead_ref
    - stanford.token:stanford.deprel

sentence:
    - stanford.sentence:misc.id
