#===============================================================================
# Standard Swedish Annotation Presets
#===============================================================================
languages:
    - swe


classes:
    sentence: segment.sentence
    named_entity: swener.ne
    token: segment.token
    "token:word": <token>:misc.word
    "token:sense": <token>:wsd.sense

presets:
    all:
        - token-annotations
        - swener
        - sentence
        - lexical_class_text
        - readability

    #====================================
    # Token Annotations
    #====================================

    token-annotations:
        - hunpos
        - saldo
        - malt
        - sentiment
        - lexical_class_token

    hunpos:
        - <token>:hunpos.pos
        - <token>:hunpos.msd

    saldo:
        - <token>:saldo.baseform
        - <token>:saldo.lemgram
        - <token>:wsd.sense
        - <token>:saldo.compwf
        - <token>:saldo.complemgram

    malt:
        - <token>:malt.deprel
        - <token>:malt.dephead_ref
        - <token>:misc.number_rel_<sentence> as ref

    sentiment:
        - <token>:sensaldo.score
        - <token>:sensaldo.label

    lexical_class_token:
        - <token>:lexical_classes.blingbring
        - <token>:lexical_classes.swefn

    #====================================
    # Structural Annotations
    #====================================

    swener:
        - swener.ne:swener.ex
        - swener.ne:swener.name
        - swener.ne:swener.type
        - swener.ne:swener.subtype

    sentence:
        - <sentence>:misc.id
        - <sentence>:geo.geo_context as geo

    lexical_class_text:
        - <text>:lexical_classes.blingbring
        - <text>:lexical_classes.swefn

    readability:
        - <text>:readability.lix
        - <text>:readability.ovix
        - <text>:readability.nk
