#===============================================================================
# Meta Data
#===============================================================================

metadata:
    # Language of the input documents, specified as ISO 639-3 code
    language: swe

    # File type of the input. Must be 'xml' or 'txt'.
    source_type: xml


#===============================================================================
# Output Settings
#===============================================================================

# Common settings for exporters
export:
    # Set to false if annotation name spaces should be kept in the export
    remove_export_namespaces: true
    # Chunk to scramble the XML export on
    scramble_on: <sentence>

# Class definitions
classes:
    sentence: segment.sentence
    token: segment.token
    "token:word": <token>:misc.word


#===============================================================================
# Module-specific Settings
#===============================================================================

segment:
    # Chunk to use for automatic sentence segmentation (typically <text> or nothing)
    paragraph_chunk: <text>
    # How to do automatic paragraph segmentation. Valid values: blanklines, linebreaks, whitespace, fsv_paragraph
    paragraph_segmenter: blanklines
    # Chunk to use for automatic sentence segmentation (typically <text> or <paragraph>)
    sentence_chunk: <text>
    # Chunk to use for automatic tokenisation
    token_chunk: <sentence>

saldo:
    precision: ""


#===============================================================================
# Korp and Installation
#===============================================================================
xml_export:
    # Export hosts and paths (targets for install_export and install_export_original)
    export_host: ""
    export_path: ""
    export_original_host: ""
    export_original_path: ""

korp:
    # Korp: password protected corpus
    protected: false

    # Remote host name for installation of both corpus data and database
    remote_host: ""

    # Paths on remote server (targets for install_corpus)
    remote_cwb_datadir: ""
    remote_corpus_registry: ""

    # Database name for relations, lemgram index and timespan
    mysql_dbname: ""

    # Installations to be made when running `sparv install`
    install:
        - "korp:install_corpus"
        - "korp:install_relations"
        - "korp:install_timespan"
        - "xml_export:install_original"
        - "xml_export:install_sentence_scrambled"
