#===============================================================================
# Meta Data
#===============================================================================

metadata:
    # Corpus ID (Machine name, only lower case ASCII letters (a-z) and "-" allowed. No white spaces.)
    id: stanford-corpus
    # Corpus name (human readable)
    name: Stanford Parser test corpus
    # Language of the input documents, specified as ISO 639-3 code
    language: eng


#===============================================================================
# Annotation Settings
#===============================================================================

xml_parser:
    # The element representing one text document. Text-level annotations will be made on this element.
    document_element: text


#===============================================================================
# Output (Export) Settings
#===============================================================================

xml_export: &xml
    # Automatic annotations to be included in the export
    annotations:
        - STANFORD.all

vrt_export: *xml
