id: stanford-corpus
name: Stanford Parser test corpus
language: eng

# Elements and attributes from the source XML that we want to be available as input for other annotations
xml_elements:
    - text

annotations:
    - text
    - <sentence>
    - <token>
    - <token:pos>
    - <token:upos>
    - <token:baseform>
    - <token:ne>
    - <token:dephead_ref>
    - <token:deprel>
    - <token:ref>

classes:
    text: text
    sentence: stanford.sentence
    token: stanford.token
    "token:word": <token>:stanford.word
    "token:ref": <token>:stanford.ref
    "token:pos": <token>:stanford.pos
    "token:upos": <token>:stanford.upos
    "token:baseform": <token>:stanford.baseform
    "token:ne": <token>:stanford.ne
    "token:dephead_ref": <token>:stanford.dephead_ref
    "token:deprel": <token>:stanford.deprel
