################################################################################
# META DATA
################################################################################

# Corpus ID (Machine name, only lower case ASCII letters (a-z) and "-" allowed. No white spaces.)
id: testkorpus
# Corpus name (human readable)
name: Testkorpus


################################################################################
# INPUT DESCRIPTION
################################################################################

# Annotations to keep from original documents. If nothing is specified, everything is kept.
original_annotations:
    - dokument as document
    - text:id
    - text:date
    - text:forfattare as author
    - i

# Elements and attributes from the source XML that we want to be available as input for other annotations
xml_elements:
    - text:date

# Chunk to use for automatic sentence segmentation
sentence_chunk: <text>

# Description of the date/time input format
dateformat:
    datetime_from: <text>:date
    datetime_to: <text>:date
    datetime_informat: "%Y-%m-%d"


################################################################################
# OUTPUT DESCRIPTION
################################################################################

# Class definitions
classes:
    text: text

# Automatic annotations to be included in the export
annotations:
    - <text>:readability.lix
    - <text>:dateformat.datefrom
    - <text>:dateformat.dateto
    - <text>:dateformat.timefrom
    - <text>:dateformat.timeto
    - <sentence>:geo.geo_context as geo
    - standard_swe_annotations
