#===============================================================================
# Meta Data
#===============================================================================

# Corpus ID (Machine name, only lower case ASCII letters (a-z) and "-" allowed. No white spaces.)
id: testkorpus
# Corpus name (human readable)
name: Testkorpus


#===============================================================================
# Annotation Settings (???)
#===============================================================================

# Elements and attributes from the source XML that we want to be available as input for other annotations
xml_elements:
    - text:date

segment:
    # Chunk to use for automatic sentence segmentation (typically text or paragraph)
    sentence_chunk: <paragraph>

# Description of the date/time input format
dateformat:
    datetime_from: <text>:date
    datetime_to: <text>:date
    datetime_informat: "%Y-%m-%d"


#===============================================================================
# Output (Export) Settings
#===============================================================================

# Annotations from original documents to include in the output. If nothing is specified, everything is kept.
original_annotations:
    - dokument as document
    - text:id
    - text:date
    - text:forfattare as author
    - i

# Automatic annotations to be included in the export
annotations:
    - SWE_DEFAULT.all
    - DATETIME.all
