#===============================================================================
# Meta Data
#===============================================================================

metadata:
    # Corpus ID (Machine name, only lower case ASCII letters (a-z) and "-" allowed. No white spaces.)
    id: testkorpus
    # Corpus name (human readable)
    name: Testkorpus


#===============================================================================
# Annotation Settings (???)
#===============================================================================

xml_parser:
    # The element representing one text document. Text-level annotations will be made on this element.
    document_element: text
    # Elements and attributes from the source XML that we want to be available as input for other annotations
    elements:
        - text:date

segment:
    # Chunk to use for automatic sentence segmentation (typically text or paragraph)
    sentence_chunk: <paragraph>

# Description of the date/time input format
dateformat:
    datetime_from: <text>:date
    datetime_to: <text>:date
    datetime_informat: "%Y-%m-%d"


#===============================================================================
# Output (Export) Settings
#===============================================================================

xml_export: &xml
    # Annotations from original documents to include in the output. If nothing is specified, everything is kept.
    source_annotations:
        - dokument as document
        - text:id
        - text:date
        - text:forfattare as author
        - i
    # Automatic annotations to be included in the export
    annotations:
        - SWE_DEFAULT.all
        - DATETIME.all
        - <token>:misc.word.affixed
        - <token>:misc.word.affixed2
        - <token>:custom.convert.upper


vrt_export: *xml


csv_export:
    # Annotations from original documents to include in the output. If nothing is specified, everything is kept.
    source_annotations:
        - text:id
        - text:date
        - text:forfattare as author
    # Automatic annotations to be included in the export
    annotations:
        - <text>:readability.lix
        - SWE_DEFAULT.sentence
        - SWE_DEFAULT.token-annotations


#===============================================================================
# Custom Annotations
#===============================================================================
custom_annotations:
    - name: misc:affix
      params:
          out: <token>:misc.word.affixed
          chunk: <token:word>
          prefix: "|"
          suffix: "|"

    - name: misc:affix
      params:
          out: <token>:misc.word.affixed2
          chunk: <token:word>
          prefix: "-"
          suffix: "-"

    - name: custom.convert:uppercase
