name: testkorpus

# Elements and attributes from the source XML that we want to be available as input for other annotations
xml_elements:
  - text:date
  - text:forfattare

sentence_chunk: <text>

annotations:
  - text
  - <sentence>
  - <token>
  - <token:pos>

classes:
    token: segment.token
    text: text
