id: testkorpus
name: Testkorpus

# Elements and attributes from the source XML that we want to be available as input for other annotations
xml_elements:
  - text:date

sentence_chunk: <text>

annotations:
  - text
  - <sentence>
  - <token>
  - <token:pos>

original_annotations:
  - text:date
  - text:forfattare>author

classes:
    token: segment.token
    text: text
