#===============================================================================
# Standard Swedish Annotation Presets
#===============================================================================
languages:
    - swe


classes:
    sentence: segment.sentence
    named_entity: swener.ne
    token: segment.token
    "token:word": <token>:misc.word
    "token:pos": <token>:hunpos.pos
    "token:msd": <token>:hunpos.msd
    "token:baseform": <token>:saldo.baseform
    "token:sense": <token>:wsd.sense
    "token:deprel": <token>:malt.deprel
    "token:dephead": <token>:malt.dephead
    "token:dephead_ref": <token>:malt.dephead_ref

presets:
    all:
        - token-annotations
        - swener
        - sentence
        - text-lexical-class
        - readability

    #====================================
    # Token Annotations
    #====================================

    token-annotations:
        - hunpos
        - saldo
        - malt
        # - stanza
        - sentiment
        - token-lexical-class

    hunpos:
        - <token>:hunpos.pos
        - <token>:hunpos.msd

    saldo:
        - <token>:saldo.baseform
        - <token>:saldo.lemgram
        - <token>:wsd.sense
        - <token>:saldo.compwf
        - <token>:saldo.complemgram

    malt:
        - <token>:malt.deprel
        - <token>:malt.dephead_ref
        - <token>:misc.number_rel_<sentence> as ref
    
    # stanza:
    #     - <token>:stanza.msd
    #     - <token>:stanza.pos
    #     - <token>:stanza.deprel
    #     - <token>:stanza.dephead_ref
    #     - <token>:misc.number_rel_<sentence> as ref

    sentiment:
        - <token>:sensaldo.sentiment_score
        - <token>:sensaldo.sentiment_label

    token-lexical-class:
        - <token>:lexical_classes.blingbring
        - <token>:lexical_classes.swefn

    #====================================
    # Structural Annotations
    #====================================

    swener:
        - swener.ne:swener.ex
        - swener.ne:swener.name
        - swener.ne:swener.type
        - swener.ne:swener.subtype

    sentence:
        - <sentence>:misc.id
        - <sentence>:geo.geo_context as geo

    text-lexical-class:
        - <text>:lexical_classes.blingbring
        - <text>:lexical_classes.swefn

    readability:
        - <text>:readability.lix
        - <text>:readability.ovix
        - <text>:readability.nk
